#!/usr/bin/python -SB

import re
import os
import sys
import glob
import distutils.dir_util

default_indent = '    '

ssh_config_fname = os.path.join(os.environ["HOME"], ".ssh", "config")
known_hosts_fname = os.path.join(os.environ["HOME"], ".ssh", "known_hosts")
keys_dest_dir = os.path.join(os.environ["HOME"], ".ssh", "anonssh_keys")
github_key_fname = "~/.ssh/anonssh_keys/id_rsa.github"


SELF = os.path.abspath(os.path.dirname(__file__))

def get_content(fname):
	with open(fname, "rb") as f:
		return f.read()


def set_content(fname, content):
	with open(fname, "wb") as f:
		return f.write(content)


def indent_style(config):
	if re.findall(re.compile(r'^\t', re.M), config):
		return '\t'
	elif re.findall(re.compile(r'^    ', re.M), config):
		return '    '
	elif re.findall(re.compile(r'^  ', re.M), config):
		return '  '
	elif re.findall(re.compile(r'^ ', re.M), config):
		return ' '
	return default_indent


def install_anonssh_keys():
	keys_src_dir = os.path.join(SELF, "anonssh_keys")
	distutils.dir_util.copy_tree(keys_src_dir, keys_dest_dir)
	for f in glob.glob(os.path.join(keys_dest_dir, "*")):
		os.chmod(f, 0600)
	print "Installed %s" % (keys_dest_dir,)


def install_known_hosts():
	try:
		old = get_content(known_hosts_fname).rstrip().split("\n")
	except IOError:
		old = []
	known_hosts = dict(github=get_content(os.path.join(SELF, "known_hosts", "github")).rstrip())
	extra = []
	installing = []
	for name, key in known_hosts.iteritems():
		if not key in old:
			extra.append(key)
			installing.append(name)
	if extra:
		set_content(known_hosts_fname, "\n".join(old + extra) + "\n")
		print "Installed known hosts for for %r to %s" % (installing, known_hosts_fname)


def main():
	install_anonssh_keys()
	install_known_hosts()

	try:
		old = get_content(ssh_config_fname)
	except IOError:
		old = ""

	if re.findall(re.compile(r"^Host github\.com$", re.M), old):
		print >>sys.stderr, "Host github.com is already configured in %s" % (ssh_config_fname,)
		return
	else:
		indent = indent_style(old)

	extra = """\
# Added by anonssh-git
Host github.com
{indent}IdentityFile {github_key_fname}
{indent}IdentitiesOnly yes
""".format(indent=indent, github_key_fname=github_key_fname)

	if old:
		extra = "\n" + extra
		if not old.endswith("\n"):
			extra = "\n" + extra

	set_content(ssh_config_fname, old + extra)

	print "Configured anonssh key in %s" % (ssh_config_fname,)


if __name__ == '__main__':
	main()
