#!/usr/bin/python -SB

import re
import os
import sys
import distutils.dir_util

default_indent = '    '

ssh_config_fname = os.path.join(os.environ["HOME"], ".ssh", "config")
keys_dest_dir = os.path.join(os.environ["HOME"], ".ssh", "anonssh_keys")
github_key_fname = "~/.ssh/anonssh_keys/id_rsa.github"


def indent_style(config):
	if re.findall(re.compile(r'^\t', re.M), config):
		return '\t'
	elif re.findall(re.compile(r'^    ', re.M), config):
		return '    '
	elif re.findall(re.compile(r'^  ', re.M), config):
		return '  '
	elif re.findall(re.compile(r'^ ', re.M), config):
		return ' '
	return default_indent


def main():
	keys_src_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), "anonssh_keys")

	try:
		with open(ssh_config_fname, "rb") as f:
			old = f.read()
	except IOError:
		old = ""

	distutils.dir_util.copy_tree(keys_src_dir, keys_dest_dir)

	if "Host github.com" in old:
		print >>sys.stderr, "Host github.com is already configured in %s" % (ssh_config_fname,)
		return
	else:
		indent = indent_style(old)

	extra = """\
# Added by anonssh-git
Host github.com
{indent}IdentityFile {github_key_fname}
{indent}IdentitiesOnly yes
""".format(indent=indent, github_key_fname=github_key_fname)

	if old:
		extra = "\n" + extra
		if not old.endswith("\n"):
			extra = "\n" + extra

	with open(ssh_config_fname, "wb") as f:
		f.write(old + extra)

	print "Configured anonssh key in %s" % (ssh_config_fname,)


if __name__ == '__main__':
	main()
